<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Anies Dilaporkan ke Bawaslu karena Serang_5c6c6e</name>
   <tag></tag>
   <elementGuidId>ecf9acdf-5156-4efe-8929-826ddd8b8ef1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='___gcse_0']/div/div/div/div[5]/div[2]/div/div/div/div[2]/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2f1e023c-ed70-4fa1-8430-00cf66d27975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gs-title</value>
      <webElementGuid>0779fb97-4df4-4b12-8304-c15cb6619b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://nasional.kompas.com/read/2024/01/09/13393791/anies-dilaporkan-ke-bawaslu-karena-serang-prabowo-di-debat-capres&amp;sa=U&amp;ved=2ahUKEwi6o9ithtKDAxW2RWcHHRbnBfYQFnoECAkQAg&amp;usg=AOvVaw33_-QGgwxm7K2IENSX5jxw</value>
      <webElementGuid>dc287851-47f1-47fc-b725-b4888e7485ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_parent</value>
      <webElementGuid>270e4275-b193-458c-a5d6-df25c9bc109f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>d4db5883-3e71-4229-bcc4-929cb8f93ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://nasional.kompas.com/read/2024/01/09/13393791/anies-dilaporkan-ke-bawaslu-karena-serang-prabowo-di-debat-capres&amp;sa=U&amp;ved=2ahUKEwi6o9ithtKDAxW2RWcHHRbnBfYQFnoECAkQAg&amp;usg=AOvVaw33_-QGgwxm7K2IENSX5jxw</value>
      <webElementGuid>fd5adc30-15ee-467e-99b6-4e333b98f1b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctorig</name>
      <type>Main</type>
      <value>https://nasional.kompas.com/read/2024/01/09/13393791/anies-dilaporkan-ke-bawaslu-karena-serang-prabowo-di-debat-capres</value>
      <webElementGuid>b960d7b9-d41a-4c33-985f-3b45db329964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Anies Dilaporkan ke Bawaslu karena Serang Prabowo di Debat ...</value>
      <webElementGuid>b1728763-edf1-4fe1-8ff3-7bd434ec858a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;___gcse_0&quot;)/div[@class=&quot;gsc-control-cse gsc-control-cse-en&quot;]/div[@class=&quot;gsc-control-wrapper-cse&quot;]/div[@class=&quot;gsc-results-wrapper-nooverlay gsc-results-wrapper-visible&quot;]/div[@class=&quot;gsc-wrapper&quot;]/div[@class=&quot;gsc-resultsbox-visible&quot;]/div[@class=&quot;gsc-resultsRoot gsc-tabData gsc-tabdActive&quot;]/div[@class=&quot;gsc-results gsc-webResult&quot;]/div[@class=&quot;gsc-expansionArea&quot;]/div[@class=&quot;gsc-webResult gsc-result&quot;]/div[@class=&quot;gs-webResult gs-result&quot;]/div[@class=&quot;gsc-thumbnail-inside&quot;]/div[@class=&quot;gs-title&quot;]/a[@class=&quot;gs-title&quot;]</value>
      <webElementGuid>742e4163-b0a0-463f-81c2-2168aea14344</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='___gcse_0']/div/div/div/div[5]/div[2]/div/div/div/div[2]/div/div/div/a</value>
      <webElementGuid>e8606167-342e-4568-b3b4-11f37abbc175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://nasional.kompas.com/read/2024/01/09/13393791/anies-dilaporkan-ke-bawaslu-karena-serang-prabowo-di-debat-capres&amp;sa=U&amp;ved=2ahUKEwi6o9ithtKDAxW2RWcHHRbnBfYQFnoECAkQAg&amp;usg=AOvVaw33_-QGgwxm7K2IENSX5jxw')]</value>
      <webElementGuid>43803011-933b-4df0-9003-b9565b92fe83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/a</value>
      <webElementGuid>5da833da-abe4-4f15-bb5f-416fac5e8268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://nasional.kompas.com/read/2024/01/09/13393791/anies-dilaporkan-ke-bawaslu-karena-serang-prabowo-di-debat-capres&amp;sa=U&amp;ved=2ahUKEwi6o9ithtKDAxW2RWcHHRbnBfYQFnoECAkQAg&amp;usg=AOvVaw33_-QGgwxm7K2IENSX5jxw' and (text() = 'Anies Dilaporkan ke Bawaslu karena Serang Prabowo di Debat ...' or . = 'Anies Dilaporkan ke Bawaslu karena Serang Prabowo di Debat ...')]</value>
      <webElementGuid>a75752e1-46a2-40c6-aeb8-44138bc8e8fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
